.idea/2joping-front.iml
.idea/misc.xml
.idea/modules.xml
.idea/vcs.xml
.idea/workspace.xml
front/.gitattributes
front/.gitignore
front/.mvn/wrapper/maven-wrapper.properties
front/mvnw
front/mvnw.cmd
front/pom.xml
front/src/main/java/com/nhnacademy/front/FrontApplication.java
front/src/main/resources/application.properties
front/src/test/java/com/nhnacademy/front/FrontApplicationTests.java

- front 서버 패키지 구조 파일 생성
- pom.xml 추가 : Lombok, Spring Web, Thymeleaf
* Devtools 보안 이슈로 추가하지 않음(추후 추가 계획)

feature : front server package

---

.idea/workspace.xml
pom.xml

layout에 네비게이션 바 표기 위한 라이브러리 추가

chore: add thymeleaf layout dependency

---

pom.xml

maven compile 안됨 -> pom.xml 오타수정

pom.xml 오타수정

---

.idea/workspace.xml
src/main/java/com/nhnacademy/twojopingfront/order/controller/OrderController.java
src/main/java/com/nhnacademy/twojopingfront/order/dto/request/PaymentRequest.java
src/main/java/com/nhnacademy/twojopingfront/order/dto/response/PaymentResponse.java
src/main/resources/application.properties
src/main/resources/static/js/order-form.js
src/main/resources/templates/component/toss-widget/checkout.html
src/main/resources/templates/component/toss-widget/success.html
src/main/resources/templates/order/order-form.html
src/main/resources/templates/order/payment-success.html

- front controller의 결제 승인 처리와 연결
- toss payment의 결제 처리 결과 간략히 보임
- 배송 정책 기반 가격 적용 아직 적용 X

feat: show toss response

---

.idea/misc.xml
.idea/workspace.xml
src/main/java/com/nhnacademy/twojopingfront/order/client/ShipmentPolicyRequestClient.java
src/main/java/com/nhnacademy/twojopingfront/order/controller/OrderController.java
src/main/java/com/nhnacademy/twojopingfront/order/dto/response/ShipmentPolicyResponseDto.java
src/main/resources/application.properties
src/main/resources/static/css/order-style.css
src/main/resources/static/js/order-form.js
src/main/resources/templates/cart/cart.html
src/main/resources/templates/component/toss-widget/checkout.html
src/main/resources/templates/order/order-form.html

- 여러 배송비 정책이 있는 것을 고려하여, DB로 가져온 배송 정책을 테이블로 정보 표시
- 도서 주문수량 조정 시 결제 정보의 가격 조정
- 주소 처리 시 상세주소 외 빈칸 존재하는 경우 alert
- 회원의 장바구니 및 도서 정보 연결
-  배송 정책 정보 기반으로 도서 구매액에 따른 배송비 조정

Feature/order cart: UI book 기능과 연동

---

src/test/java/com/nhnacademy/twojopingfront/bookset/book/controller/BookControllerTest.java

핫픽스로 오타난거 수정하면서 테스트 코드 수정을 까먹어서
테스트 코드에 있는 경로도 수정했씁니다.

refactor: update test code

---

src/main/resources/templates/admin/shipment/shipment-policy-form.html

배송정책 view에서 최소주문 금액 validation 0이상으로 수정

fix: min order amount modify

---

src/main/resources/templates/layout/mainpage-layout.html
src/main/resources/templates/layout/menu-footer-layout.html
src/main/resources/templates/layout/mypage-layout.html

header-hotfix

---

src/main/java/com/nhnacademy/twojopingfront/bookset/book/client/BookClient.java
src/main/java/com/nhnacademy/twojopingfront/bookset/book/controller/BookController.java
src/main/java/com/nhnacademy/twojopingfront/bookset/book/dto/request/BookCreateHtmlRequestDto.java
src/main/java/com/nhnacademy/twojopingfront/bookset/book/dto/request/BookCreateRequestDto.java
src/main/java/com/nhnacademy/twojopingfront/bookset/book/dto/request/ImageUploadRequestDto.java
src/main/java/com/nhnacademy/twojopingfront/bookset/book/dto/request/ImageUrlRequestDto.java
src/main/java/com/nhnacademy/twojopingfront/bookset/book/dto/response/BookCreateResponseDto.java
src/main/java/com/nhnacademy/twojopingfront/bookset/book/service/BookService.java
src/main/java/com/nhnacademy/twojopingfront/bookset/category/dto/response/CategoryResponseDto.java
src/main/java/com/nhnacademy/twojopingfront/bookset/contributor/dto/response/ContributorResponseDto.java
src/main/java/com/nhnacademy/twojopingfront/common/error/exception/image/ImageUploadException.java
src/main/resources/templates/bookset/book/admin-get-booklist.html
src/main/resources/templates/bookset/book/book-register.html

feat: 도서 단독 등록 프론트 연결

---

src/main/resources/static/css/book-detail-style.css
src/main/resources/static/css/mypage-style.css
src/main/resources/static/js/book-detail-button.js
src/main/resources/templates/bookset/book/bookdetails.html
src/main/resources/templates/layout/mainpage-layout.html

feat-book-detail-page-design

---

src/main/java/com/nhnacademy/twojopingfront/bookset/book/client/BookClient.java
src/main/java/com/nhnacademy/twojopingfront/bookset/book/controller/BookController.java
src/main/java/com/nhnacademy/twojopingfront/bookset/book/dto/request/BookCreateHtmlRequestDto.java
src/main/java/com/nhnacademy/twojopingfront/bookset/book/service/BookService.java
src/main/java/com/nhnacademy/twojopingfront/bookset/contributor/dto/response/ContributorNameRoleResponseDto.java
src/main/resources/templates/bookset/book/admin-get-booklist.html
src/main/resources/templates/bookset/book/book-register.html

feat: 도서 삭제 기능 구현

---

src/main/java/com/nhnacademy/twojopingfront/bookset/book/client/BookClient.java
src/main/java/com/nhnacademy/twojopingfront/bookset/book/controller/BookController.java
src/main/java/com/nhnacademy/twojopingfront/bookset/book/dto/request/BookCreateHtmlRequestDto.java
src/main/java/com/nhnacademy/twojopingfront/bookset/book/service/BookService.java
src/main/java/com/nhnacademy/twojopingfront/bookset/contributor/dto/response/ContributorNameRoleResponseDto.java
src/main/resources/templates/bookset/book/book-register.html

feat: implement book register

---

src/main/java/com/nhnacademy/twojopingfront/admin/couponPolicy/client/CouponPolicyClient.java
src/main/java/com/nhnacademy/twojopingfront/admin/couponPolicy/controller/CouponPolicyController.java
src/main/java/com/nhnacademy/twojopingfront/admin/couponPolicy/dto/CouponPolicyResponseDto.java
src/main/java/com/nhnacademy/twojopingfront/admin/couponPolicy/dto/CreateCouponPolicyRequest.java
src/main/java/com/nhnacademy/twojopingfront/admin/couponPolicy/dto/UpdateCouponPolicyRequest.java
src/main/java/com/nhnacademy/twojopingfront/admin/couponPolicy/enums/DiscountType.java
src/main/java/com/nhnacademy/twojopingfront/admin/couponPolicy/service/CouponPolicyService.java
src/main/java/com/nhnacademy/twojopingfront/admin/pointType/dto/PointTypeResponseDto.java
src/main/resources/templates/admin/coupon-policy/coupon-policy-list.html
src/main/resources/templates/admin/coupon-policy/create-coupon-policy.html
src/main/resources/templates/admin/coupon-policy/edit-coupon-policy.html
src/main/resources/templates/admin/point-type/edit-point-type.html
src/main/resources/templates/admin/point-type/point-type-list.html
src/main/resources/templates/layout/admin-layout.html

admin coupon-policy view 구현했습니다.
생성, 수정, 비활성화 모두 동작합니다
package 성공했습니다.

feat: coupon-policy view 구현

---

src/main/java/com/nhnacademy/twojopingfront/bookset/book/controller/BookController.java
src/main/resources/static/css/book-detail-style.css
src/main/resources/templates/bookset/book/bookdetails.html
src/main/resources/templates/bookset/search/search-list.html
src/main/resources/templates/common/index.html

feat: book detail shipment-policy 추가

---

src/main/java/com/nhnacademy/twojopingfront/bookset/book/controller/BookController.java
src/main/resources/templates/bookset/book/admin-get-booklist.html

feaet: add success and failure message

---

src/main/resources/static/css/admin-index-style.css
src/main/resources/templates/bookset/book/admin-get-booklist.html

관리자 도서 목록 페이지에 대한 레이아웃을 업데이트하고 스타일 추가했습니다.

 style: update layout and add custom styles for admin booklist page #98

---

src/main/resources/templates/bookset/book/admin-get-booklist.html

style: add style

---

src/main/resources/static/css/book-update-style.css
src/main/resources/templates/bookset/book/book-update.html

style: add style for book update

---

src/main/java/com/nhnacademy/twojopingfront/like/adaptor/LikeAdaptor.java
src/main/java/com/nhnacademy/twojopingfront/like/dto/response/MemberLikeResponseDto.java
src/main/java/com/nhnacademy/twojopingfront/user/mypage/controller/MypageViewController.java
src/main/resources/templates/layout/mainpage-layout.html
src/main/resources/templates/layout/menu-footer-layout.html
src/main/resources/templates/layout/mypage-layout.html
src/main/resources/templates/user/mypage/liked-items.html

feat-user-like

---

src/main/resources/static/css/default-layout.css
src/main/resources/static/css/mypage-style.css
src/main/resources/templates/layout/mainpage-layout.html
src/main/resources/templates/layout/menu-footer-layout.html
src/main/resources/templates/layout/mypage-layout.html
src/main/resources/templates/layout/order-layout.html

fix: rename profile dropdown class and show dropdown

---

src/main/java/com/nhnacademy/twojopingfront/order/dto/request/OrderRequest.java
src/main/resources/static/js/order-form.js

fix: add more dto data to transfer

---

src/main/java/com/nhnacademy/twojopingfront/user/member/adaptor/MemberAdaptor.java
src/main/java/com/nhnacademy/twojopingfront/user/member/controller/MemberAddressRestController.java
src/main/java/com/nhnacademy/twojopingfront/user/member/dto/request/AddressUpdateRequestDto.java
src/main/java/com/nhnacademy/twojopingfront/user/member/dto/response/AddressDeleteResponseDto.java
src/main/java/com/nhnacademy/twojopingfront/user/member/dto/response/AddressUpdateResponseDto.java
src/main/resources/static/js/mypage-address.js
src/main/resources/templates/user/mypage/address-list.html

feat-member-address-update-delete

---

src/main/java/com/nhnacademy/twojopingfront/bookset/elastic/repository/impl/ElasticRepositoryImpl.java
src/main/resources/static/css/admin-index-style.css
src/main/resources/static/js/admin-layout.js
src/main/resources/templates/layout/admin-layout.html

엘라스틱 서치  동의어 유의어 처리
"synonym_filter": {
"type": "synonym",
"synonyms": [
"과학, science",
"음식, food, 요리, cook",
"컴퓨터, computer",
"자바, java"
]
}

feat: elasticsearch synonym

---

src/main/java/com/nhnacademy/twojopingfront/bookset/book/controller/BookController.java
src/main/resources/static/js/book-update.js
src/main/resources/templates/bookset/book/book-update.html

책 설명 수정 시 WYSIWYG(위즈윅) Editor를 사용해서 등록하도록 수정했습니다. 
추가적으로 controller에서 책 수정시 예외처리 부분 수정했습니다.

feat: add WYSIWYG Editor for book description

---

src/main/java/com/nhnacademy/twojopingfront/bookset/book/controller/BookController.java

controller에서 책 비활성화시 예외처리 부분 수정했습니다.

feat: remove try catch for book delete

---

src/main/java/com/nhnacademy/twojopingfront/bookset/like/client/LikeClient.java
src/main/java/com/nhnacademy/twojopingfront/cart/controller/CartController.java
src/main/java/com/nhnacademy/twojopingfront/common/decoder/CustomFeignErrorDecoder.java
src/main/java/com/nhnacademy/twojopingfront/common/filter/JwtAuthenticationFilter.java
src/main/java/com/nhnacademy/twojopingfront/order/client/OrderClient.java
src/main/java/com/nhnacademy/twojopingfront/order/controller/OrderController.java
src/main/java/com/nhnacademy/twojopingfront/order/service/OrderService.java
src/main/resources/static/js/order-form.js
src/main/resources/templates/order/order-form.html

- 주문 시 장바구니 삭제 처리
- 전화번호 입력시 자동으로 `-` 추가

fix: fix order failure when order in account

---

src/main/java/com/nhnacademy/twojopingfront/common/favicon/FaviconController.java

hotfix-favicon

---

src/main/resources/static/js/order-form.js

fix: correct phone number format
